name: Luckyblock
version: ${project.version}
main: lenlino.com.luckyblock.Luckyblock
api-version: 1.16
commands:
  lbget:
    description: ラッキーブロック獲得
  lbgive:
    description: ラッキブロック渡す
  lbdo:
    description: ラッキブロックの内容実行
