name: Luckyblock
version: ${project.version}
main: lenlino.com.luckyblock.Luckyblock
api-version: 1.16
commands:
  lbget:
    description: ラッキーブロック獲得
    permission: luckyblock.get
  lbgive:
    description: ラッキーブロック渡す
    permission: luckyblock.give
  lbdo:
    description: ラッキーブロック内容実行 ほかの人に実行させるなら/lbdo number playerNameにする
    permission: luckyblock.do
  lbadd:
    description: ドロップするアイテム追加
    permission: luckyblock.add
  lbgetlist:
    description: 追加したアイテムの名まえ一覧表示
    permission: luckyblock.getlist
  lbremove:
    description: 追加したアイテムを削除
    permission: luckyblock.remove
  lbreload:
    description: このプラグインを再起動する
    permission: luckyblock.reload